services: 
  web: 
    image: nginx:latest
    container_name: nginx-web
    restart: unless-stopped
    ports:
      - "8080:80"
#    volumes: 
#      - ./html:/usr/share/nginx/html:ro #ro: read-only